name: max_app
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  auto_route: 7.9.0
  dio: ^5.4.3+1
  pretty_dio_logger: ^1.3.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  freezed: ^2.5.2
  json_serializable: ^6.7.1
  flutter_bloc: ^8.1.5
  bloc: ^8.1.4
  get_it: ^7.3.0
  injectable: ^1.5.3
  injectable_generator: ^1.5.4
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  auto_route_generator: 7.3.2

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/png/

flutter_intl:
  enabled: true
